DELETE FROM `wlodc_techhub`.`topic_presenter_table`;
DELETE FROM `wlodc_techhub`.`topic`;
DELETE FROM `wlodc_techhub`.`presenter`;
DELETE FROM `wlodc_techhub`.`white_list_user`;
DELETE FROM `wlodc_techhub`.`poster`;
DELETE FROM `wlodc_techhub`.`choice`;
DELETE FROM `wlodc_techhub`.`question`;

INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'Opening Key Notes', 'topiclogo', 'Opening Key Notes', 'PN_TR01', '11:00 To 11:15');
INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'Evidence Based Management', 'topiclogo', 'Evidence Based Management', 'PN_TR01', '11:15 To 12:15');
INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'Tools for Agile Ceremonies', 'topiclogo', 'Tools for Agile Ceremonies', 'PN_TR02', '11:15 To 12:15');
INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'LESS - Game', 'topiclogo', 'LESS - Game', 'PN_TR01', '12:15 To 13:15');
INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'SAFe', 'topiclogo', 'SAFe ', 'PN_TR02', '12:15 To 13:15');
INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'Kaun Banega Agile Boss', 'topiclogo', 'Kaun Banega Agile Boss', 'PN_TR01', '14:15 To 15:15');
INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'Agile Ki Adalat', 'topiclogo', 'Agile Ki Adalat', 'PN_TR02', '14:15 To 15:15');
INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'Retrospective of Retrospectives', 'topiclogo', 'Retrospective of Retrospectives', 'PN_TR01', '15:15 To 16:15');
INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'Agile Testing extension and Product Owner Certifications', 'topiclogo', 'Agile Testing extension and Product Owner Certifications', 'PN_TR02', '15:15 To 16:15');
INSERT INTO `wlodc_techhub`.`topic` (`record_state`, `version`, `description`, `image_url`, `name`, `room_number`, `time_slot`) VALUES ('ACTIVE', '0', 'Closing Notes and Prize Distribution', 'topiclogo', 'Closing Notes and Prize Distribution', 'PN_TR01', '16:15 To 16:45');

INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A175004', 'Sujata', 'Salunkhe', 'sujata.salunkhe@atos.net', '9920934918', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A169104', 'Abhijit', 'Gurav', 'abhijit.gurav@atos.net', '9920017220', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A154224', 'Brajesh', 'Singh', 'brajesh.singh@worldline.com', '9820346746', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A502903', 'Amit', 'Tiwari', 'amit.tiwari@atos.net', '7709579269', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A135844', 'Samir', 'Umrikar', 'samir.umrikar@atos.net', '9819743603', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A602289', 'Mahesh', 'Mandhare', 'mahesh.mandhare@atos.net', '9665868428', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A167127', 'Gourgobinda', 'Acharya', 'satyabrata.acharya@atos.net', '9011063930', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A567156', 'Sameer', 'Ahire', 'sameer.ahire@atos.net', '9545345106', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A676491', 'Dhrubajyoti', 'Bhattacharjee', 'dhrubajyoti.bhattacharjee@atos.net', '7350014619', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A682255', 'Taniya', 'Negi', 'taniya.negi@atos.net', '9075342763', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A167064', 'Vijay', 'Varade', 'vijay.varade@atos.net', '9850007545', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A661116', 'Pratigyan', 'Manjhi', 'pratigyan.manjhi@atos.net', '8446532806', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A687313', 'Siddharth', 'Joshi', 'siddharth.joshi@atos.net', '8928432049', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A173366', 'Reetu', 'Shinde', 'reetu.shinde@atos.net', '9702607262', 'presenterphoto');
INSERT INTO `wlodc_techhub`.`presenter` (`record_state`, `version`, `user_id`, `first_name`, `last_name`, `email`, `mobile`, `image_url`) VALUES ('ACTIVE', '0', 'A165124', 'Shalaka', 'Kathe', 'shalaka.kathe@atos.net', '9923959196', 'presenterphoto');

INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Opening Key Notes'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A175004'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Evidence Based Management'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A165124'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='LESS - Game'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A169104'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='LESS - Game'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A154224'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Kaun Banega Agile Boss'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A502903'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Kaun Banega Agile Boss'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A135844'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Kaun Banega Agile Boss'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A602289'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Retrospective of Retrospectives'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A167127'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Retrospective of Retrospectives'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A567156'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Tools for Agile Ceremonies'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A676491'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Tools for Agile Ceremonies'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A682255'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='SAFe'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A502903'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='SAFe'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A167064'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Agile Ki Adalat'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A154224'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Agile Ki Adalat'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A661116'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Agile Ki Adalat'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A687313'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Agile Testing extension and Product Owner Certifications'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A173366'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Agile Testing extension and Product Owner Certifications'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A165124'));
INSERT INTO `wlodc_techhub`.`topic_presenter_table` (`topic_id`, `presenter_id`) VALUES ((SELECT `id` FROM `wlodc_techhub`.`topic` WHERE `name`='Closing Notes and Prize Distribution'), (SELECT `id` FROM `wlodc_techhub`.`presenter` WHERE `user_id`='A175004'));

INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A120065');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A558026');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A558025');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A506970');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A502903');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A175004');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'IN03381');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'IN03294');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A135844');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A169104');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A154224');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A165124');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A168178');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A569292');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A511951');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A563628');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A590797');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A565887');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A598954');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A601388');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A168964');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A147866');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A637323');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A528966');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A641777');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A648003');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A615532');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A602291');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A173366');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A700216');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A622793');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A702001');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A664450');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A668566');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A688925');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A683896');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A574888');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A574107');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A661114');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A680666');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A687416');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A584632');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A666831');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A565891');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A680181');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A589618');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A678702');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A594969');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A593030');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A696817');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A579585');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A661230');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A681911');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A569292');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A686457');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A707294');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A686301');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A681910');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A500398');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A608461');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A646866');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A620518');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A672117');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A694054');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A653190');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A513642');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A526744');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A187875');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A670955');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A664162');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A707296');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A565073');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A610463');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A506970');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A704349');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A680781');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A618037');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A566319');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A181771');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A622922');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A572392');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A596037');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A707146');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A503995');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A594679');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A622663');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A635627');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A606008');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A546900');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A513632');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A603988');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A585858');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A163382');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A567156');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A167127');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A185473');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A167064');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A699841');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A164650');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A506826');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A180548');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A676491');
INSERT INTO `wlodc_techhub`.`white_list_user` (`record_state`, `version`, `user_id`) VALUES ('ACTIVE', '0', 'A682255');

INSERT INTO `wlodc_techhub`.`poster` (`record_state`, `version`, `name`, `participants`,`url`) VALUES ('ACTIVE', '0', 'Agile in nutshell', 'Arihant Jain, Prathama Morye, Mahesh Mandlik, Anjali Chachlani','../../assets/imgs/posters/1536146666466-d0cecadb-2800-4fb9-9ae0-4e8518442b3a.jpg');
INSERT INTO `wlodc_techhub`.`poster` (`record_state`, `version`, `name`, `participants`,`url`) VALUES ('ACTIVE', '0', 'Agile League Atos', 'Mangesh Kumbhar, Shraddha, Pooja, Mangesh Ghodake','../../assets/imgs/posters/1536146641513-99220e82-ad2b-4f7f-b5f8-d365bbb60a65.jpg');
INSERT INTO `wlodc_techhub`.`poster` (`record_state`, `version`, `name`, `participants`,`url`) VALUES ('ACTIVE', '0', 'Its Agile', 'Komal Sarode','../../assets/imgs/posters/1536146597554-c2527572-95a2-4286-bb1e-35a575fcde67.jpg');
INSERT INTO `wlodc_techhub`.`poster` (`record_state`, `version`, `name`, `participants`,`url`) VALUES ('ACTIVE', '0', 'Building Home in Agile way', 'Priyanka C, Mrunal K, Charu M, Laxman M','../../assets/imgs/posters/1536146548353-c6148a3b-9a39-4e30-a21f-45c1a0d6e054.jpg');
INSERT INTO `wlodc_techhub`.`poster` (`record_state`, `version`, `name`, `participants`,`url`) VALUES ('ACTIVE', '0', 'AGILE', 'Vasudha Chaudhari, Sneha Thatte, Amit Makhija, Swapnil Gadekar','../../assets/imgs/posters/1536146469842-9fdca013-ae62-409e-96e5-ca519d97f89f.jpg');
INSERT INTO `wlodc_techhub`.`poster` (`record_state`, `version`, `name`, `participants`,`url`) VALUES ('ACTIVE', '0', 'Agile in T-20', 'Tahir Dange, Satendra Singh, Aishwarya K, Komal Laddha','../../assets/imgs/posters/1536146737065-f68a8d29-b7e7-4a53-a84c-54a0fd53691d.jpg');
INSERT INTO `wlodc_techhub`.`poster` (`record_state`, `version`, `name`, `participants`,`url`) VALUES ('ACTIVE', '0', 'Scrum Agile', 'Prakash M, Vinayak B, Om G','../../assets/imgs/posters/1536146700177-a72a5414-9c41-4f79-8e7a-5ea46158f81e.jpg');
INSERT INTO `wlodc_techhub`.`poster` (`record_state`, `version`, `name`, `participants`,`url`) VALUES ('ACTIVE', '0', 'Agile Bahubali', 'Pratigyan, Monika, Ishita, Siddharth','../../assets/imgs/posters/1536146798663-b66dcdaf-b063-432e-9c4d-6d1a7d10848a.jpg');

INSERT INTO `wlodc_techhub`.`question` (`record_state`, `version`, `number`, `description`, `question_type`, `answer_type`) VALUES ('ACTIVE', '0', 1, 'How relevant were the topics for the event?', 'FEEDBACK', 'SINGLE_CHOICE');
INSERT INTO `wlodc_techhub`.`question` (`record_state`, `version`, `number`, `description`, `question_type`, `answer_type`) VALUES ('ACTIVE', '0', 2, 'Do you think the learning from this event will be useful to you?', 'FEEDBACK', 'SINGLE_CHOICE');
INSERT INTO `wlodc_techhub`.`question` (`record_state`, `version`, `number`, `description`, `question_type`, `answer_type`) VALUES ('ACTIVE', '0', 3, 'How well was the event organized?', 'FEEDBACK', 'SINGLE_CHOICE');
INSERT INTO `wlodc_techhub`.`question` (`record_state`, `version`, `number`, `description`, `question_type`, `answer_type`) VALUES ('ACTIVE', '0', 4, 'Give any suggestions / feedback', 'FEEDBACK', 'LONG_TEXT');
INSERT INTO `wlodc_techhub`.`question` (`record_state`, `version`, `number`, `description`, `question_type`, `answer_type`) VALUES ('ACTIVE', '0', 5, 'Overall rating (scale 1 to 5, with 5 being maximum)', 'FEEDBACK', 'SINGLE_SELECT');

INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 1, 'All topics were relevant', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=1));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 2, 'Most topics were relevant', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=1));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 3, 'Most topics were NOT relevant', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=1));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 4, 'No relevance at all', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=1));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 1, 'Very much', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=2));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 2, 'Yes', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=2));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 3, 'To a small extent', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=2));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 4, 'Not at all', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=2));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 1, 'Excellently organized', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=3));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 2, 'Overall ok', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=3));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 3, 'Overall not so good', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=3));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 4, 'Completely unorganized', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=3));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 1, 'Rating - 1', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=5));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 2, 'Rating - 2', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=5));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 3, 'Rating - 3', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=5));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 4, 'Rating - 4', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=5));
INSERT INTO `wlodc_techhub`.`choice` (`record_state`, `version`, `number`, `description`, `question_id`) VALUES ('ACTIVE', '0', 5, 'Rating - 5', (SELECT id FROM `wlodc_techhub`.`question` WHERE `number`=5));